# Generated by Django 2.2.12 on 2021-06-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210610_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
