# Generated by Django 3.1.5 on 2022-01-02 10:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210613_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, null=True)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'APRIL'), ('May', 'MAY'), ('June', 'JUNE'), ('Jule', 'JULE'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=9)),
                ('year', models.IntegerField(choices=[(2021, 2021), (2022, 2022)], default=2022, max_length=4)),
                ('is_deadline', models.BooleanField(default=True)),
                ('deadline', models.DateField(default=datetime.date(2022, 1, 22))),
                ('is_paid', models.BooleanField(default=False)),
                ('amount_of_lessons', models.IntegerField(default=1, max_length=4)),
                ('canceled_lessons', models.IntegerField(default=0, max_length=4)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itf_order_id', models.IntegerField(blank=True, null=True)),
                ('last_massage', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.payment')),
            ],
        ),
    ]
