# Generated by Django 5.0.7 on 2024-07-11 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_order_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="deadline",
            field=models.DateField(default=datetime.date(2024, 7, 31)),
        ),
        migrations.AlterField(
            model_name="payment",
            name="year",
            field=models.IntegerField(
                choices=[(2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)],
                default=2024,
                max_length=4,
            ),
        ),
    ]
