# Generated by Django 5.0.7 on 2024-10-09 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_payment_deadline_alter_payment_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="deadline",
            field=models.DateField(default=datetime.date(2024, 10, 29)),
        ),
    ]
