# Generated by Django 5.0.7 on 2024-10-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_payment_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount_of_lessons",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="payment",
            name="canceled_lessons",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="payment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="year",
            field=models.IntegerField(
                choices=[(2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)],
                default=2024,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
