# Generated by Django 2.2.12 on 2021-06-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210609_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description22',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
