# Generated by Django 3.1.5 on 2021-06-07 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_auto_20210607_1430'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('other_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsectionitems',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AddField(
            model_name='ourteamsectionitems',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='other_content.homeourteamsection'),
        ),
        migrations.AddField(
            model_name='ourteamsectionitems',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AddField(
            model_name='news',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursessectionitems',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursessectionitems',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='other_content.homecoursessection'),
        ),
    ]
