# Generated by Django 3.1.5 on 2021-06-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_content', '0002_auto_20210607_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectsection1',
            name='position',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
