# Generated by Django 5.0.7 on 2024-07-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("other_content", "0003_auto_20210609_2145"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
