# Generated by Django 5.0.7 on 2024-10-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("other_content", "0005_alter_contactusmassage_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
